steps:
  # set aws credentials
  - id: aws credentials
    name: ubunut
    entrypoint: "bash"
    args:
      - "c"
      - |
        echo 'Setting AWS CLI credentials...'
        mkdir -p ~/.aws
  #       echo "[default]\nregion = us-east-1" >> ~/.aws/config
  #       echo "[default]\naws_access_key_id = ${AWS_ACCESS_KEY_ID}\naws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials
  # # initialize the working Terraform directory
  # - id: terraform init
  #   name: hashicorp/terraform:0.12.26
  #   entrypoint: "sh"
  #   args: ["cd tfstate && terraform init"]
  # # create an execution plan
  # - id: terraform plan
  #   name: hashicorp/terraform:0.12.26
  #   entrypoint: "sh"
  #   args: ["cd tfstate && terraform plan"]
  # # apply the new or updated resources
  # - id: terraform apply
  #   name: hashicorp/terraform:0.12.26
  #   entrypoint: "sh"
  #   args: ["cd tfstate && terraform apply -auto-approve"]
